[build]
    command = "npm run build"
    publish = "public"

[[redirects]]
    from = "/ama"
    to = "https://github.com/bradgarropy/ama#readme"
    status = 301

[[redirects]]
    from = "/dotfiles"
    to = "https://github.com/bradgarropy/dotfiles"
    status = 301

[[redirects]]
    from = "/netlify"
    to = "https://app.netlify.com"
    status = 301

[[redirects]]
    from = "/stream"
    to = "https://twitch.tv/bradgarropy"
    status = 301

[[redirects]]
    from = "/codetunes"
    to = "https://youtube.com/playlist?list=PL6Mu1AMmTL-vlrGehLTnA_MCjI4Bjx92r"
    status = 301

[[redirects]]
    from = "/discord"
    to = "https://discord.gg/WxtUPSF"
    status = 301

[[plugins]]
    package = "netlify-plugin-gatsby-cache"
