name: "ğŸ›³ï¸ lighthouse"

on: pull_request

jobs:
    lighthouse:
        name: "ğŸ›³ï¸ lighthouse"
        runs-on: ubuntu-latest
        steps:
            - name: "ğŸ“š checkout"
              uses: actions/checkout@v2.3.4
            - name: "ğŸŸ¢ node"
              uses: actions/setup-node@v2.1.4
              with:
                  node-version: 14
                  registry-url: https://registry.npmjs.org/
            - name: "â³ wait for netlify"
              uses: jakepartusch/wait-for-netlify-action@v1.3
              id: netlify
              with:
                  site_name: "bradgarropy"
                  max_timeout: 60
            - name: "ğŸ›³ï¸ lhci"
              env:
                  LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}
              run: |
                  npm install --global @lhci/cli@0.8.2
                  lhci autorun --collect.url=${{steps.netlify.outputs.url}}
            - name: "ğŸ›³ï¸ lighthouse-ci-action"
              uses: treosh/lighthouse-ci-action@v8
              env:
                  LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}
              with:
                  urls: ${{steps.netlify.outputs.url}}
                  uploadArtifacts: true
                  temporaryPublicStorage: true
            - name: "ğŸ›³ï¸ lighthouse-check-action"
              uses: foo-software/lighthouse-check-action@master
              with:
                  urls: ${{steps.netlify.outputs.url}}
                  gitHubAccessToken: ${{secrets.LIGHTHOUSE_CHECK_ACTION_ACCESS_TOKEN}}
