name: "üõ≥Ô∏è lighthouse"

on: pull_request

jobs:
    lighthouse:
        name: "üõ≥Ô∏è lighthouse"
        runs-on: ubuntu-latest
        steps:
            - name: "üü¢ node"
              uses: actions/setup-node@v2.1.4
              with:
                  node-version: 14
                  registry-url: https://registry.npmjs.org/
            - name: Waiting for 200 from the Netlify Preview
              uses: jakepartusch/wait-for-netlify-action@v1.3
              id: netlify
              with:
                  site_name: "bradgarropy"
                  max_timeout: 60
            - name: "üõ≥Ô∏è lhci"
              env:
                  LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}
              run: |
                  npm install --global @lhci/cli@0.8.2
                  lhci autorun --collect.url=${{steps.netlify.outputs.url}}
            - name: "üõ≥Ô∏è lighthouse-ci-action"
              uses: treosh/lighthouse-ci-action@v8
              env:
                  LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}
              with:
                  urls: ${{steps.netlify.outputs.url}}
                  uploadArtifacts: true
                  temporaryPublicStorage: true
            - name: "üõ≥Ô∏è lighthouse-check-action"
              uses: foo-software/lighthouse-check-action@master
              with:
                  urls: ${{steps.netlify.outputs.url}}
                  gitHubAccessToken: ${{secrets.LIGHTHOUSE_CHECK_ACTION_ACCESS_TOKEN}}
